level_1 = [
'WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWW',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'                NNNNNN                 ',
'                NNNNNN                 ',
'                NNNNNN                 ',
'                NNNNNN                 ',
'                NNNNNN                 ',
'                NNNNNN                 ',
'                NNNNNN                 ',
'W                                     W',
'W                                     W',
'W                                     W',
'W       S                             W',
'W                                     W',
'W                                     W',
'W                                     W',
'WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWW']
level_2 = [
'WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWW',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'W                                     W',
'                WWWWWW                 ',
'                WWWWWW                 ',
'                WWWWWW                 ',
'                WWWWWW                 ',
'                WWWWWW                 ',
'                WWWWWW                 ',
'                WWWWWW                 ',
'W                                     W',
'W                                     W',
'W                                     W',
'W       S                             W',
'W                                     W',
'W                                     W',
'W                                     W',
'WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWW']